<!DOCTYPE html>
<html>

<head>
    <title>Promise对象</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <script>
        //1. Promise的含义
        {
            //Promise对象有以下两个特点:

            //（1）对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：Pending（进行中）、Resolved（已完成，又称Fulfilled）和Rejected（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。

            //（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从Pending变为Resolved和从Pending变为Rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果。就算改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。

            //Promise也有一些缺点。
            //首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。第三，当处于Pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

        }
        //2.基本用法
        {
            //用法：

            // var promise = new Promise(function(resolve, reject) {
            //     // ... some code

            //     if ( /* 异步操作成功 */ ) {
            //         resolve(value);
            //     } else {
            //         reject(error);
            //     }
            // });

            // promise.then(function(value) {
            //     // success
            // }, function(error) {
            //     // failure
            // });

            let timeout = function(ms) {
                return new Promise((resolve, reject) => {
                    setTimeout(resolve, ms, 'done');
                });
            }

            timeout(1).then((value) => {
                console.log(value);
            });

            //Promise新建后就会立即执行。
            let promise = new Promise(function(resolve, reject) {
                console.log('Promise');
                resolve();
            });

            promise.then(function() {
                console.log('Resolved.');
            });
            console.log('Hi!');

            let loadImageAsync = function(url) {
                return new Promise(function(resolve, reject) {
                    var image = new Image();
                    image.src = url;

                    image.onload = function() {
                        resolve(image);
                    };

                    image.onerror = function() {
                        reject(new Error('Could not load image at ' + url));
                    };

                });
            }
            loadImageAsync("./test1.JPG").then(
                (value) => {
                    console.log(value);
                }, (error) => {
                    console.log(error);
                }
            );

            let getJSON = function(url) {
                var promise = new Promise(function(resolve, reject) {
                    var client = new XMLHttpRequest();
                    client.open("GET", url);
                    client.onreadystatechange = handler;
                    client.responseType = "json";
                    client.setRequestHeader("Accept", "application/json");
                    client.send();

                    function handler() {
                        if (this.readyState !== 4) {
                            return;
                        }
                        if (this.status === 200) {
                            resolve(this.response);
                        } else {
                            reject(new Error(this.statusText));
                        }
                    };
                });

                return promise;
            };

            getJSON("http://posts.json").then(function(json) {
                console.log('Contents: ' + json);
            }, function(error) {
                console.error('出错了', error);
            });

            let p1 = new Promise(function(resolve, reject) {
                setTimeout(() => reject(new Error('fail')), 1000)
            });

            let p2 = new Promise(function(resolve, reject) {
                setTimeout(() => resolve(p1), 1000)
            });

            p2.then(result => console.log(result))
                .catch(error => console.log(error));
        }
        //3.Promise.prototype.then
        {
            //Promise实例具有then方法，也就是说，then方法是定义在原型对象Promise.prototype上的。它的作用是为Promise实例添加状态改变时的回调函数。前面说过，then方法的第一个参数是Resolved状态的回调函数，第二个参数（可选）是Rejected状态的回调函数。then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。
            let promise = new Promise((resolve, reject) => {
                console.log("start first promise");
                resolve("first result");
            });
            promise.then((value) => {
                console.log("print first promise's result:" + value);
                return "second result";
            }).then((value) => {
                console.log("print second promise's result:" + value);
            });;

            let promise2 = new Promise((resolve, reject) => {
                resolve(x + 2);
            });
            promise2.then((value) => {}, (erro) => {
                return "first promise2 thrown exception"
            }).then((value) => {
                console.log("print second promise2's result:" + value);
            });;
        }
        //4.Promise.prototype.catch
        {
            //catch方法返回的还是一个Promise对象，因此后面还可以接着调用then方法。
            let someAsyncThing = function() {
                return new Promise(function(resolve, reject) {
                    // 下面一行会报错，因为x没有声明
                    resolve(x + 2);
                });
            };

            let aa = someAsyncThing().catch(function(error) {
                console.log('oh no', error);
            }).then(function() {
                console.log('carry on');
            });
            // oh no [ReferenceError: x is not defined]
            // carry on

            someAsyncThing().then(function() {
                //
            }).catch(function(error) {
                console.log('oh no', error);
                // 下面一行会报错，因为y没有声明
                y + 2;
            }).catch(function(error) {
                console.log('carry on', error);
            });
            // oh no [ReferenceError: x is not defined]
            // carry on [ReferenceError: y is not defined]
        }
        //5. Promise.all()
        {
            //Promise.all方法用于将多个Promise实例，包装成一个新的Promise实例。
            //var p = Promise.all([p1, p2, p3]);

            //Promise.all方法接受一个数组(可以不是数组，但必须具有Iterator接口，且返回的每个成员都是Promise实例)作为参数，p1、p2、p3都是Promise对象的实例，如果不是，就会先调用下面讲到的Promise.resolve方法，将参数转为Promise实例，再进一步处理。

            //p的状态由p1、 p2、 p3决定， 分成两种情况。

            //（ 1） 只有p1、 p2、 p3的状态都变成fulfilled， p的状态才会变成fulfilled， 此时p1、 p2、 p3的返回值组成一个数组， 传递给p的回调函数。

            //（ 2） 只要p1、 p2、 p3之中有一个被rejected， p的状态就变成rejected， 此时第一个被reject的实例的返回值， 会传递给p的回调函数。
            let getJSON = function(url) {
                var promise = new Promise(function(resolve, reject) {
                    var client = new XMLHttpRequest();
                    client.open("GET", url);
                    client.onreadystatechange = handler;
                    client.responseType = "json";
                    client.setRequestHeader("Accept", "application/json");
                    client.send();

                    function handler() {
                        if (this.readyState !== 4) {
                            return;
                        }
                        if (this.status === 200) {
                            resolve(this.response);
                        } else {
                            reject(new Error(this.statusText));
                        }
                    };
                });

                return promise;
            };

            // 生成一个Promise对象的数组
            var promises = [2, 3, 5, 7, 11, 13].map(function(id) {
                return getJSON("http://post/" + id + ".json");
            });

            Promise.all(promises).then(function(posts) {
                console.log("all promise's results:", posts);
            }).catch(function(reason) {
                console.log("first reject promise's error:", reason);
            });
        }
        //6. Promise.race()
        {
            //Promise.race方法同样是将多个Promise实例，包装成一个新的Promise实例。
            //var p = Promise.race([p1, p2, p3]);
            //只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的Promise实例的返回值，就传递给p的回调函数。

            //Promise.race方法的参数与Promise.all方法一样， 如果不是Promise实例， 就会先调用下面讲到的Promise.resolve方法， 将参数转为Promise实例， 再进一步处理。

            let p = Promise.race([
                fetch('http://resource-that-may-take-a-while'),
                new Promise(function(resolve, reject) {
                    setTimeout(() => reject(new Error('request timeout')), 5000)
                })
            ]);
            p.then(response => console.log(response))
            p.catch(error => console.log(error));
            //上面代码中，如果5秒之内fetch方法无法返回结果，变量p的状态就会变为rejected，从而触发catch方法指定的回调函数。
        }
        //7. Promise.resolve()
        {
            //Promise.resolve方法将现有对象转为Promise对象，实例状态为resolve。
            Promise.resolve('foo');
            // 等价于
            new Promise(resolve => resolve('foo'));
            //Promise.resolve方法的参数分成四种情况。
            //（1） 参数是一个Promise实例
            //如果参数是Promise实例， 那么Promise.resolve将不做任何修改、 原封不动地返回这个实例。

            //（ 2） 参数是一个thenable对象
            //thenable对象指的是具有then方法的对象， 比如下面这个对象。
            let thenable = {
                then: function(resolve, reject) {
                    resolve(42);
                }
            };
            //Promise.resolve方法会将这个对象转为Promise对象，然后就立即执行thenable对象的then方法
            let p1 = Promise.resolve(thenable);
            p1.then((value) => {
                console.log("thenable then's result:", value);
            });

            //（3）参数不是具有then方法的对象，或根本就不是对象
            //如果参数是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的Promise对象，状态为Resolved
            let p2 = Promise.resolve("Hello");
            p2.then((value) => console.log(value));

            //（4）不带有任何参数
            //Promise.resolve方法允许调用时不带参数，直接返回一个Resolved状态的Promise对象。
            let p3 = Promise.resolve();

            p3.then(function() {
                // ...
            });
            //p3 是在本轮“事件循环”（event loop）的结束时立即执行。
            setTimeout(function() {
                console.log('three');
            }, 0);
            Promise.resolve().then(function() {
                console.log('two');
            });
            console.log('one');
            // one
            // two
            // three
        }
        //8. Promise.reject()
        {
            //Promise.reject(reason)方法也会返回一个新的Promise实例，该实例的状态为rejected。它的参数用法与Promise.resolve方法完全一致
            var p = Promise.reject('promise.resolve 出错了');
            // 等同于
            //var p = new Promise((resolve, reject) => reject('promise.resolve 出错了'))

            p.then(null, function(s) {
                console.log(s)
            });
            // 出错了
        }
        //9. 两个有用的附加方法
        {
            //(1)done() 
            //done方法，总是处于回调链的尾端，保证抛出任何可能出现的错误
            //asyncFunc().then(f1).catch(r1).then(f2).done();

            //它的实现代码相当简单。
            Promise.prototype.done = function(onFulfilled, onRejected) {
                this.then(onFulfilled, onRejected)
                    .catch(function(reason) {
                        // 抛出一个全局错误
                        setTimeout(() => {
                            throw reason
                        }, 0);
                    });
            };

            let promise = new Promise((resolve, reject) => {
                throw new Error("Done inner error");
            });
            promise.done((error) => console.log("done value:", error));

            //(2)finally() 
            //finally方法用于指定不管Promise对象最后状态如何，都会执行的操作。它与done方法的最大区别，它接受一个普通的回调函数作为参数，该函数不管怎样都必须执行
            //server.listen(0).then(function () {// run test}).finally(server.stop);
            Promise.prototype.finally = function(callback) {
                let P = this.constructor;
                return this.then(
                    value => P.resolve(callback()).then(() => value),
                    reason => P.resolve(callback()).then(() => {
                        throw reason
                    })
                );
            };
            let promise2 = new Promise((resolve, reject) => {
                throw new Error("Finally inner errro");
            });
            promise2.finally((value) => console.log("finally value:", value));
        }
    </script>
</body>

</html>